### ISSUE TITLE
[SUBTASK of story #81] Implement a feature that allows the user to add vehicles to their favourites tab. This will allow easy access and comparison between vehicles.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#104]

**Comment by JeremyCrete** [comment]
This subtask is part of story #81 and involves implementing a new feature to enhance user experience. The feature aims to allow users to add vehicles to their favorites tab for easy access and comparison.

Key aspects of this implementation include:

- Adding a functionality to mark vehicles as favorites.
- Creating a favorites tab where users can view their saved vehicles.
- Allowing users to easily add and remove vehicles from their favorites list.
- Ensuring that the favorites tab provides clear and concise information about each saved vehicle.

This feature will enhance user engagement and provide a convenient way for users to keep track of their preferred vehicles.

**Comment by Niravanaa** [comment]
Completed without an entire view of favorite vehicles but rather a search filter.
