### ISSUE TITLE
Add Ability to Manage Account Info

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#154]
### 🚀 Summary:

Add the necessary functionality for users to manage their:
- Email
- Password
- Name

### 📜 Description:

- [ ] Add ability for users to change their password
- [ ] Add ability for users to change their email address
- [ ] Add ability for users to change their name

**Comment by briantkatch** [comment]
This is not an approved subtask of #143, changing subject line. @CarciDev

**Comment by briantkatch** [comment]
Nice to have for next sprint

**Comment by briantkatch** [comment]
Project completed, closing.
