### ISSUE TITLE
[USER STORY] Check-in Process

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#157]
### 🚀 Story Summary:

As a user, I want to easily check in for my reservation so that I can quickly confirm my booking details, complete necessary documentation, and start using my rented car with minimal delays.

### 📋 Tasks / Acceptance tests (AT):

- [x] #158
- [x] #159
- [x] #160
- [x] #161
- [x] #162
- [x] #163
- [x] #164
- [x] #165

### 📝 Additional Context:
- the interface should provide clear instructions and support for first-time users to ensure a smooth and efficient check-in experience.
- focusing on ease of use, efficiency, and security.
- The Check-In Notes feature should be designed to be as flexible as possible, allowing users to freely input any information they consider important for their rental experience.

**Comment by briantkatch** [comment]
Remaining feature (email) for next sprint

**Comment by briantkatch** [comment]
Remaining feature (email) cancelled.
