### ISSUE TITLE
[SUBTASK of story #157] Design a check-in interface: Create a user-friendly interface in the app that clearly displays reservation details such as the model of the car, pickup location, rental period, and price.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#158]
Develop a user-friendly interface within the car rental app to display reservation details clearly, including car model, pickup location, rental period, and price.
Exit Criteria: The interface is designed and implemented with all essential reservation details visible at a glance. Users can easily understand and navigate through the displayed information without encountering any usability issues.

**Comment by briantkatch** [comment]
Closing as completed
