### ISSUE TITLE
[SUBTASK of story #157] identity verification: Develop a feature for users to verify their identity by uploading a photo of their driver's license and taking a selfie.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#159]
(IF WE HAVE TIME)

Develop a feature allowing users to verify their identity by uploading a photo of their driver's license and taking a selfie.
Exit Criteria:

Users can initiate the identity verification process.
The feature guides users through uploading their driver's license photo and taking a selfie.
Uploaded photos are processed successfully.
Users receive confirmation upon successful verification or clear instructions for any verification issues.

**Comment by briantkatch** [comment]
This is probably a *reach* feature / possible extra feature in the final sprint. In particular, most of the selfie-identity-verification APIs that exist cost serious money.

How the identity verification is supposed to work is the CSR visually examines the ID and records the number during the check-in flow.

**Comment by JeremyCrete** [comment]
when I though of it I was like this is for sure a reach but I decided to add it like an extra thing just if we have time

**Comment by briantkatch** [comment]
Closing as infeasible / won’t do
