### ISSUE TITLE
[SUBTASK of story #157] Integrate payment processing: Facilitate the completion of any outstanding payments via a secure in-app payment system.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#160]
Implement secure in-app payment system for users to complete outstanding payments conveniently.
Exit Criteria:

Users can access payment processing feature within the app.
Securely process payment information.
Completed payments reflected accurately in user's account.
Clear confirmation or instructions provided post payment completion or error handling.

**Comment by briantkatch** [comment]
Completed to prof standard in pr #200
