### ISSUE TITLE
[SUBTASK of story #157] Document upload feature: Provide a section for users to upload necessary documents, such as proof of insurance, if required.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#161]
Develop a section within the application allowing users to upload necessary documents, such as proof of insurance, if required. This feature enables users to submit essential documentation seamlessly.
Exit Criteria:

Users can access the document upload section within the application.
The feature allows users to select and upload documents from their device storage.
Uploaded documents are processed and stored securely.
Users receive confirmation upon successful document submission.
In case of errors or issues during document upload, an error prompt is shown on screen.

**Comment by briantkatch** [comment]
Closing as out of scope
