### ISSUE TITLE
[SUBTASK of story #157] Customer support access: Ensure users have quick access to customer support from the check-in interface for any inquiries or issues that arise during the process.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#163]
Enable direct access to customer support from the check-in interface for user inquiries or issues.
Exit Criteria:

Customer support link/button visibly placed on the check-in interface.
Users can easily initiate a support request.
Support requests promptly directed to relevant channels.
Clear instructions provided for expected support response method.
Users receive confirmation upon submitting a support request.
Alternative contact methods available for any technical issues.

**Comment by briantkatch** [comment]
Closing as check in is done by csr per assigned sprint
