### ISSUE TITLE
[SUBTASK of story #157] Enable digital agreements: Allow users to read and agree to the rental terms and conditions through the app, including any insurance options.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#164]
Develop a feature allowing users to review and accept rental terms, including insurance options, within the app.
Exit Criteria:

Rental terms and insurance options accessible within the app.
User-friendly interface guides users through agreement review and acceptance.
Users can digitally accept terms and insurance selections.
Confirmation of agreement acceptance provided.
Clear instructions for users in case of disagreement or issues.

**Comment by briantkatch** [comment]
Closing as completed
