### ISSUE TITLE
[SUBTASK of story #157] Incorporate Check-In Notes: Add a feature allowing users to input any special requests or additional information (e.g., preferred car features, child seat requests, late arrival notifications) during the check-in process.

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#165]
Integrate feature for users to input special requests or additional information during check-in (e.g., car preferences, child seat requests).
Exit Criteria:

Users access a section for adding check-in notes.
Input of special requests is user-friendly.
Check-in notes are saved with the reservation.
Users receive confirmation upon submission.
Error handling in place for technical issues.

**Comment by briantkatch** [comment]
Closing as checkinnotes became checkinreporteddamages in the schema in pr #200
