### ISSUE TITLE
[USER STORY] Check-Out Process

### ISSUE THREAD

**Issue by annabelzecchel** [NathanGrenier/SOEN-341#167]
### 🚀 Story Summary:

As a user, I want to efficiently complete the check-out process when returning my rented car so that I can confirm any additional charges, ensure the vehicle is returned in good condition, and finalize the rental agreement quickly.

### 📋 Tasks / Acceptance Tests (AT):

- [x] #168
- [x] #177
- [x] #178
- [x] #179
- [ ] #180
- [x] #181
- [ ] #182
- [x] #183

**Comment by briantkatch** [comment]
Remaining task (email) for sprint 4
