### ISSUE TITLE
Use a Specific Version of Node.js

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#24]
I'm not sure what the best version of node to use is. Once that's determined, follow this [guide](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json) on how to specify the node version to use in package.json.

The GitHub workflows will also have to have their node versions updated.

**Comment by CarciDev** [comment]
I think we should use **20.10.0 LTS** since it's the most stable version of Node.js.

**Comment by briantkatch** [comment]
Agreed with David. LTS unless there’s something really compelling that’s needed from the current branch.
