### ISSUE TITLE
Dev environment does not start because Postgres root password not initialized

### ISSUE THREAD

**Issue by briantkatch** [NathanGrenier/SOEN-341#33]
<img width="998" alt="image" src="https://github.com/NathanGrenier/SOEN-341/assets/10686291/3b409215-dee4-4f5f-ab15-f7bd3c44e5cb">

**Comment by NathanGrenier** [comment]
make sure to create a .env file. You can find out what you need to add to it in the projects README

**Comment by briantkatch** [comment]
Will try and update. I thought we had default values.

**Comment by NathanGrenier** [comment]
I'm assuming this issue was resolved and am closing it for now. Feel free to reopen it if the issue persists.
