### ISSUE TITLE
Add new GitHub workflows for develop

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#55]
### 🚀 Summary:

Create the workflow to run when a PR is merged into the develop branch.

### 📜 Description:

**Could be possible to reuse the same db branch and just apply the new migrations and seeds**

On push to develop:
- [x] Delete old preview database branch created upon PR creation
- [x] Apply migrations
- [x] Deploy to [develop url](https://soen-341-develop.vercel.app/) on vercel

**Comment by briantkatch** [comment]
Just to be clear, the production app will still run on master, not on develop, correct? The vercel deploy of develop is just for QA purposes?

**Comment by NathanGrenier** [comment]
Ya, develop will be used as a staging environment for the combination of different features. A merge to main from develop will mark a new release.

There are also preview environment that are automatically created in every pr.

I might make a wiki page explaining the workflow and available environments.
