### ISSUE TITLE
Add Description to Readme

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#64]
### 🚀 Summary:

Add Project Description to Readme (in project `root`)

### 📜 Description:

The description should explain the following:
- [x] Description of the project
- [x] Team members and their roles
- [x] Project approach and technology
  - [x] Review the technology wiki page and update if necessary
- [x] A link to the site

**Comment by CarciDev** [comment]
Also : Project approach and technology (Use template)
