### ISSUE TITLE
Creating minutes for meeting (meeting #1)

### ISSUE THREAD

**Issue by CarciDev** [NathanGrenier/SOEN-341#71]
### 🚀 Summary:

Ideally done on wiki. Also put notes

### 📜 Description:

[Detailed description of the task]

**Comment by Niravanaa** [comment]
Added a section to the "Meeting Minutes" section describing [our first meeting](https://github.com/NathanGrenier/SOEN-341/wiki/Meeting-Minutes#meeting-1).
