### ISSUE TITLE
[USER STORY] CRUD Operations on Reservations

### ISSUE THREAD

**Issue by Niravanaa** [NathanGrenier/SOEN-341#79]
### 🚀 Story Summary:

As a System Administrator,
I want to be able to perform CRUD operations on reservations
So that I can manage the booking system effectively and troubleshoot any issues that arise.

#### System Administrator
 - [ ] #112
 - [ ] #113
 - [ ] #114
 - [ ] #115
 - [ ] #116

### Additional Context
**For System Administrators (Sysadmins):**

1. **Viewing Reservations:**
   - Sysadmins might access a centralized admin dashboard or reservation management system.
   - They can filter and search reservations based on various criteria such as reservation ID, customer name, pickup date, etc.
   - The dashboard might provide an overview of all reservations along with their statuses (e.g., pending, confirmed, canceled).

2. **Creating New Reservations:**
   - Sysadmins could have a form or interface to input reservation details on behalf of customers.
   - This form would include fields such as customer information, vehicle type, pickup and return dates, and any additional services requested.
   - Once submitted, the reservation should be added to the system and appear in the list of reservations.

3. **Modifying Reservations:**
   - Sysadmins might have the ability to edit existing reservation details.
   - They would navigate to the specific reservation through the admin interface and update the relevant information, such as pickup and return dates, vehicle type, or additional services.
   - Any changes made should be reflected in the system immediately.

4. **Canceling Reservations:**
   - Sysadmins could initiate the cancellation process for a reservation upon request or as needed.
   - They would locate the reservation in the system and mark it as canceled, updating the status accordingly.
   - The cancellation should trigger any necessary actions such as refund processing or updating inventory availability.

**Comment by briantkatch** [comment]
👍

I believe CSR is out of scope for sprint 1 so we'll need to plan/backlog the tasks accordingly
