### ISSUE TITLE
[USER STORY] CRUD Operations of Customers and Vehicles from System Administrator's Persective

### ISSUE THREAD

**Issue by CarciDev** [NathanGrenier/SOEN-341#80]
## 🚀 Story Summary:

The objective of this story is to provide a functional feature, regarding the ability for the System Administrator (SA) to operate on Customers and Vehicles via CRUD principles. It is important to note that anything to do with reservations will be discussed in #79.

### Core Features:
>As a **System Administrator**, I want to be able to **perform CRUD operations** on **Vehicles**. 
>As a **System Administrator**, I want to be able to **perform CRUD operations** on **Customers**. 

## **Derivation of Sub-Tasks of CRUD for Vehicles and Customer from SA's perspective:**

>It is important to note, that the acceptance criteria are assumptions, and can change at any time, especially if client (professor) requests specific features / implementations. 

### CREATE
- [ ] #117

- [ ] #118

### READ
- [ ] #119

- [ ] #120

### UPDATE
- [ ] #121

- [ ] #122

### DELETE (DISABLE)
- [ ] #123

### OTHER CONDITIONS
- [ ] #124

According to the schema at #78, deleting is in fact disabling an account.

**Comment by briantkatch** [comment]
👍

I believe CSR is out of scope for sprint 1 so we'll need to plan/backlog the tasks accordingly

**Comment by CarciDev** [comment]
> 👍
> 
> I believe CSR is out of scope for sprint 1 so we'll need to plan/backlog the tasks accordingly

Understood. Will derive tasks regarding the focus on CRUD's SA's POV on Vehicles and Users.
