### ISSUE TITLE
[USER STORY] Browse vehicles for rent

### ISSUE THREAD

**Issue by JeremyCrete** [NathanGrenier/SOEN-341#81]
### 🚀 Story Summary:

As a user, I want to browse the available vehicles for rent so that I can choose the best vehicle for my needs.

### 📋 Tasks:

- [x] #99
- [x] #100
- [x] #101
- [x] #102
- [x] #103
- [x] #105
- [ ] #104
- [ ] #106

### 📝 Additional Context:
- The user should be able to easily access and navigate the "Browse Vehicles" section from the main navigation menu.
- The displayed information about the vehicles should be clear and comprehensive in order to aid the user to make an informed decision. 
- Introducing filtering options depending on the size of the vehicle caters to diverse users preferences and needs. This feature will enhance the platforms usability and appeal.
- The addition of a favourites tab allows the user to save and compare different vehicles depending on their needs.
- Testing the browser experience across different browsers and devices ensures that the platform maintains optimal responsiveness and usability. 
- To facilitate the user's ability to save and manage their favourite vehicles, a table/relationship will be implemented to store user-selected favourite rentals.
- Providing a seamless hand-off mechanism for selected dates and vehicle data into the booking flow simplifies the reservation process, making it easier for the users to complete their booking with minimal effort.

**Comment by briantkatch** [comment]
👍

Will need to implement a table/relationship for the user's favourite vehicles

Will need a way to hand off the selected dates and vehicle into the booking flow
